@startuml jisdvis-prometheus
!include plantumlcolor.inc
participant Prometheus as p
participant Exporter as e
participant Debugger as d
e <- d: hit breakpoint/set value **a=0**
p -> e: pull metrics
p <- e: response metrics
note left
metrics
a: 0
end note
e <- d: hit breakpoint/set value **a=1**
e <- d: hit breakpoint/set value **a=2**
e <- d: hit breakpoint/set value **a=3**
e <- d: hit breakpoint/set value **a=4**
p -> e: pull metrics
p <- e: response metrics
note left
metrics
a: 4
end note
@enduml

@startuml jisdvis-prometheus-exporter-debugger
!include plantumlcolor.inc
participant Exporter as e
participant Debugger as d
participant TargetVM as t
d <- t: breakpoint hit(a=1)
e <- d: notify(ValueInfo)
note left 
metrics
a: 1
end note
d <- t: breakpoint hit(a=2)
e <- d: notify(ValueInfo)
note left 
metrics
a: 2
end note
@enduml

@startuml jisdvis-es
!include plantumlcolor.inc
participant Elasticsearch as p
participant JsonExporter as e
participant Debugger as d
e <- d: hit breakpoint/set value **a=0**
note left
metricsCache
a: 0
end note
e <- d: hit breakpoint/set value **a=1**
note left
metricsCache
a: 0
a: 1
end note
e <- d: hit breakpoint/set value **a=2**
note left
metricsCache
a: 0
a: 1
a: 2
end note
p <- e: post metrics(per 1s)
note left
metrics
a: 0
a: 1
a: 2
end note
e <- d: hit breakpoint/set value **a=3**
note left
metricsCache
a: 3
end note
@enduml

@startuml jisdvis-es-exporter-debugger
!include plantumlcolor.inc
participant JsonExporter as e
participant Debugger as d
participant TargetVM as t
d <- t: breakpoint hit(a=1)
activate d
e <- d: notify(ValueInfo)
deactivate d
note left 
metricsCache
a: 1
end note
d <- t: breakpoint hit(a=2)
activate d
e <- d: notify(ValueInfo)
deactivate d
note left 
metricsCache
a: 1
a: 2
end note
@enduml
