skinparam {
  defaultFontColor #4c3f52
  backgroundColor #ffffff
  borderColor #828282

  noteFontColor #4c3f52
  noteBackgroundColor #ffffff
  noteBorderColor #3c2f41

  monochrome true
}

skinparam sequence {
  ArrowColor #828282

  LifeLineBorderColor #3c2f41
  LifeLineBackgroundColor #ffffff

  ActorBorderColor #3c2f41
  ActorBackgroundColor #ffffff
  ActorFontStyle bold

  ParticipantBorderColor #3c2f41
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #d05a6e
  ParticipantFontStyle bold

  BoxBorderColor #3c2f41
  BoxBackgroundColor #ffffff
  BoxFontColor #d05a6e
  BoxBorder 1
}

skinparam state {
  ArrowColor #3c2f41
  StartColor #3c2f41
  EndColor #3c2f41
  BackgroundColor #ffffff
  BorderColor #3c2f41
}