#!/bin/bash

PROJECT_DIR=/Users/saku/Workspace/2020/JISDLab/JISD/test/src/jisd/analysis/FLtest1
PROJECT_PATH=/Users/saku/Workspace/2020/JISDLab/flacoco/examples/exampleFL1/FLtest1
_output="${PROJECT_DIR}.csv"

debug_cmd() {
  local _agent_lib="-agentlib:jdwp=transport=dt_socket,server=y,address=25432,suspend=y"
  local _cp=./test/src/jisd/analysis/FLtest1/target/classes:./test/src/jisd/analysis/FLtest1/target/test-classes:/Users/saku/Workspace/2020/JISDLab/JISD/test/src/jisd/analysis/junit-4.13.2.jar:/Users/saku/Workspace/2020/JISDLab/JISD/test/src/jisd/analysis/hamcrest-all-1.3.jar
  local _test_class=fr.FLtest1.CalculatorTest
  java $_agent_lib -cp $_cp org.junit.runner.JUnitCore $_test_class &> /dev/null
}

fl_cmd() {
  java -jar /Users/saku/Workspace/2020/JISDLab/flacoco/target/flacoco-1.0.6-SNAPSHOT-jar-with-dependencies.jar \
   --projectpath $PROJECT_PATH --methodBased --format CSV -o $_output  > /Users/saku/Workspace/2020/JISDLab/JISD/test/src/jisd/analysis/out
  echo $_output
}

z_cmd() {
  java -cp /Users/saku/Workspace/2020/JISDLab/JISD/test/src/jisd/analysis/com.gzoltar.cli-1.7.3.jar \
   com.gzoltar.cli.Main --help #--outputFile $_output
  echo $_output
}

case $1 in
  debug) debug_cmd;;
  fl) fl_cmd;;
  z) z_cmd;;
  *) echo "$USAGE" 1>&2; exit 1;;
esac
